// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainComponentManagementSystem.Context;

#nullable disable

namespace TrainComponentManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainComponentManagementSystem.Models.TrainComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAssignQuantity")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UniqueNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("UniqueNumber")
                        .IsUnique();

                    b.ToTable("TrainComponents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Engine",
                            UniqueNumber = "ENG123"
                        },
                        new
                        {
                            Id = 2,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Passenger Car",
                            UniqueNumber = "PAS456"
                        },
                        new
                        {
                            Id = 3,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Freight Car",
                            UniqueNumber = "FRT789"
                        },
                        new
                        {
                            Id = 4,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Wheel",
                            UniqueNumber = "WHL101"
                        },
                        new
                        {
                            Id = 5,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Seat",
                            UniqueNumber = "STS234"
                        },
                        new
                        {
                            Id = 6,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Window",
                            UniqueNumber = "WIN567"
                        },
                        new
                        {
                            Id = 7,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Door",
                            UniqueNumber = "DR123"
                        },
                        new
                        {
                            Id = 8,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Control Panel",
                            UniqueNumber = "CTL987"
                        },
                        new
                        {
                            Id = 9,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Light",
                            UniqueNumber = "LGT456"
                        },
                        new
                        {
                            Id = 10,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Brake",
                            UniqueNumber = "BRK789"
                        },
                        new
                        {
                            Id = 11,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Bolt",
                            UniqueNumber = "BLT321"
                        },
                        new
                        {
                            Id = 12,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Nut",
                            UniqueNumber = "NUT654"
                        },
                        new
                        {
                            Id = 13,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Engine Hood",
                            UniqueNumber = "EH789"
                        },
                        new
                        {
                            Id = 14,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Axle",
                            UniqueNumber = "AX456"
                        },
                        new
                        {
                            Id = 15,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Piston",
                            UniqueNumber = "PST789"
                        },
                        new
                        {
                            Id = 16,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Handrail",
                            UniqueNumber = "HND234"
                        },
                        new
                        {
                            Id = 17,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Step",
                            UniqueNumber = "STP567"
                        },
                        new
                        {
                            Id = 18,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Roof",
                            UniqueNumber = "RF123"
                        },
                        new
                        {
                            Id = 19,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Air Conditioner",
                            UniqueNumber = "AC789"
                        },
                        new
                        {
                            Id = 20,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Flooring",
                            UniqueNumber = "FLR456"
                        },
                        new
                        {
                            Id = 21,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Mirror",
                            UniqueNumber = "MRR789"
                        },
                        new
                        {
                            Id = 22,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Horn",
                            UniqueNumber = "HRN321"
                        },
                        new
                        {
                            Id = 23,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Coupler",
                            UniqueNumber = "CPL654"
                        },
                        new
                        {
                            Id = 24,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Hinge",
                            UniqueNumber = "HNG987"
                        },
                        new
                        {
                            Id = 25,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Ladder",
                            UniqueNumber = "LDR456"
                        },
                        new
                        {
                            Id = 26,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Paint",
                            UniqueNumber = "PNT789"
                        },
                        new
                        {
                            Id = 27,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Decal",
                            UniqueNumber = "DCL321"
                        },
                        new
                        {
                            Id = 28,
                            CanAssignQuantity = true,
                            IsDeleted = false,
                            Name = "Gauge",
                            UniqueNumber = "GGS654"
                        },
                        new
                        {
                            Id = 29,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Battery",
                            UniqueNumber = "BTR987"
                        },
                        new
                        {
                            Id = 30,
                            CanAssignQuantity = false,
                            IsDeleted = false,
                            Name = "Radiator",
                            UniqueNumber = "RDR456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
